dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

services:
  - redis-server

before_script:
  - npm install
  - cp ./config/travis/dnb_tst2_app6_s1_wb_cert_key.pem ~
  - cp ./config/travis/dnb_tst2_app6_s1_wb_cert_pub.pem ~
  - cp ./config/travis/data.tar ~
  - sudo service redis-server stop
  - sleep 10
  - sudo cat /etc/redis/redis.conf
  - sudo sed -i 's|appendonly no|appendonly yes|g' /etc/redis/redis.conf
  - sudo sed -i "s|# requirepass foobared|requirepass ${DNB_ENV_APP_S2_DB_PASS}|g" /etc/redis/redis.conf
  - sudo cat /etc/redis/redis.conf
  - sudo ls -al  /var/lib/redis
  - sudo find /var/lib/redis -mindepth 1 -delete
  - sudo tar -xvf ~/data.tar -C /var/lib/redis --strip 1 
  - sudo chown redis:redis /var/lib/redis/appendonly.aof
  - sudo chmod 660 /var/lib/redis/appendonly.aof 
  - sudo ls -al  /var/lib/redis
  - sudo service redis-server start
  - sleep 20

script:
  - sudo ls -al /var/log/
  - sudo cat /var/log/redis-server/redis-server.log
  - swagger project start &
  - sleep 10
  - swagger project test
