language: node_js
node_js:
  - "6"

services:
  - redis-server

before_script:
  - npm install
  - cp ./config/travis/dnb_tst2_app6_s1_wb_cert_key.pem ~
  - cp ./config/travis/dnb_tst2_app6_s1_wb_cert_pub.pem ~
  - ls /
  - ls /data
  #- cp ./config/travis/data.tar ~
  #- sudo service redis-server stop
  #- sleep 10
  #- find /data -mindepth 1 -delete
  #- echo 'reqirepass $...' > config 
  #- tar -xvf ~/data.tar -C .


script:
  - swagger project start &
  - sleep 10
  - swagger project test
